name: Azure security for Pull Requests

on:
  pull_request:
    branches:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prevent file change
        uses: xalvarez/prevent-file-change-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: .*\azure-pipelines.yml
